### PR TITLE
UIDS-75 remove description prop from FormGroup

### LINKED ISSUE #75: Remove description prop from FormGroup
Once all uses of FormGroup in the main app have been updated to use the helperText prop we should deprecate `description`.

### PR DESCRIPTION
**Pull request by davidmferris**
Closes #75

### CODE REVIEW

**Review by rsaris — APPROVED** [review]
Does this come with the version bump or was that version bump somewhere else?

**Comment by davidmferris** [comment]
This is such a minor change I figured I'd either bump a minor version later or include with the next major update (like adding Card). It's backwards compatible so it doesn't harm anything to wait on this.

**Comment by rsaris** [comment]
Will this not break the release like it did last time we changed this repo w/o updating the version number?

**Comment by davidmferris** [comment]
No, that happened because i manually updated the package tarball without updating the refs in the app. You can merge as much stuff as you want safely here without needing to bump the version every time.

**Review by rroppolo — APPROVED** [review]

**Pull request merged**
