### PR TITLE
Fix tests for new paths

### PR DESCRIPTION
**Pull request by brianCollinsUI**
Screen Shot 2022-07-25 at 6 22 37 AM

### CODE REVIEW

**Comment by brianCollinsUI** [comment]
Not sure we even want Percy any longer since we are using Chromatic. So let me know once we have made that decision / bought a plan etc

**Comment by jasonbasuil** [comment]
> Not sure we even want Percy any longer since we are using Chromatic. So let me know once we have made that decision / bought a plan etc

@brianCollinsUI I think I would be for just using Chromatic. Would be nice to not have to write out these tests every time we create new stories. I do have a PR #681 that changes the build cadence to nightly just like Percy.

**Comment by brianCollinsUI** [comment]
OK - sounds good. We should just delete this stuff then- will make another branch for that in a bit if that is ok

**Comment by jasonbasuil** [comment]
> OK - sounds good. We should just delete this stuff then- will make another branch for that in a bit if that is ok

Sounds good. Appreciate it Brian! ⭐

**Pull request closed without merging**
